# IN THIS FILE WE CREATE THE CONNECTION TO THE DATABASE
# BY GETTING THE VALUE THROUGH AN ENVIRONMENT VARIABLE
# BY DOING THIS I AVOID SHOWING PASSWORDS
import os
from sqlalchemy import create_engine

DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL, future=True)
